### PR TITLE
fix: invalid table crashes the toMarkdown conversion bug

### LINKED ISSUE #22: Invalid table crashes the toMarkdown conversion
The importer crashes if `<table></table>` is present into the dom - see https://github.com/adobe/helix-importer-ui/issues/80

Debugging shows that root cause is in the `toMarkdown` conversion:

```
     TypeError: Cannot set properties of undefined (setting 'maxWidth')
      at Table.toMarkdown (...helix-importer/node_modules/@adobe/mdast-util-gridtables/src/to-markdown.js:238:26)
      at Object.gridTable (...helix-importer/node_modules/@adobe/mdast-util-gridtables/src/to-markdown.js:528:28)
```

While this could be captured on the importer side, I think it also makes sense to make sure the conversion does not brutally crashes here. Interesting, there is a division by 0 (numCols = 0) which gives `Infinity` has result and then array out of index.

### PR DESCRIPTION
**Pull request by kptdobe**
Fix #22

The conversion output of an invalid table (no columns found) is an empty string. Naturally, this is not bidirectional, it just makes sure the conversion does not crash.

### CODE REVIEW

File: src/to-markdown.js [hunk 1]
```diff
@@ -221,6 +221,9 @@ class Table {
       }
     }
 
+    // stop processing if no columns found
+    if (cols.length === 0) return '';
```
Comment (tripodsan) [inline src/to-markdown.js:225]:
```suggestion
    if (cols.length === 0) {
      return '';
    }
```

**Review by tripodsan — APPROVED** [review]
